sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular/cli
- npm install -g karma
- npm install
- npm run build

script: npm run test

deploy:
  provider: heroku
  api_key:
    secure: "e01ce2a9-5c8c-468a-916f-b7b7579b4083"
  app: pro-angular-staging
